# Generated by Django 5.0.1 on 2024-01-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='vor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
