# Generated by Django 5.0.1 on 2024-01-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_cadastro_vor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='contaminante',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
