# Generated by Django 5.0.1 on 2024-01-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0003_alter_cadastro_cas_alter_cadastro_contaminante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
