# Generated by Django 5.0.1 on 2024-01-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0004_alter_cadastro_cas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='abe_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='abe_nc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='fec_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='fec_nc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='vor_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
